name: k6 Performance Test

on:
  push:
    branches:
      - main  
      

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg software-properties-common
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Install k6-reporter
        run: |
          curl -sL https://github.com/szkiba/k6-reporter/releases/latest/download/install.sh | bash

      - name: Run k6 and export summary
        run: |
          k6 run --summary-export=summary.json load-test.js
          k6-reporter --out=report.html summary.json

      - name: Upload HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: k6-html-report
          path: report.html
